server:
  port: 8011

spring:
  application:
    name: springclouddemo

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7010/eureka
      defaultZone: http://eureka7010.com:7010/eureka/,http://eureka7011.com:7011/eureka/

  instance:
    instance-id: springclouddemo8011
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: springclouddemo_provider_8011
  build.version: 1.0-SNAPSHOT
